### ISSUE TITLE
Support for PDF page number mapping in converted Markdown files

### ISSUE THREAD

**Issue by xcvil** [opendatalab/MinerU#1190]
**Is your feature request related to a problem? Please describe.**
**您的特性请求是否与某个问题相关？请描述。**
Currently when converting PDF to Markdown, the mapping between Markdown content and original PDF page numbers is lost. This makes it difficult to reference back to the original PDF document.

**Describe the solution you'd like**
**描述您期望的解决方案**
- Add support for preserving PDF page numbers in the converted Markdown files
- Allow users to easily locate content in the original PDF using these page number references

**Describe alternatives you've considered**
**描述您已考虑的替代方案**
1. Using HTML comments 
```markdown
Content from first page
<!-- page 1 -->
```
2.Using hidden HTML tags
```markdown
Content from first page
<span class="page" data-page="1"></span>
```

**Comment by myhloli** [comment]
Since standard Markdown is written continuously and does not have the concept of page numbers, we use a `content_list.json` file to store additional information in a rich text format.
![image](https://github.com/user-attachments/assets/a5fdbcd0-ffca-40ae-bb01-2fb70b7e13fe)
![image](https://github.com/user-attachments/assets/358ff477-fcf0-4c6e-9c17-404a130d29a1)
