### ISSUE TITLE
Layout Bug

### ISSUE THREAD

**Issue by Schorakbi** [opendatalab/MinerU#450]
### Description of the bug | 错误描述

The layout detector model not detecting certain sentences

### How to reproduce the bug | 如何复现

When i try to parse this pdf the layout is not detecting certain sentences and not detecting certain formulas too 
[Uploading math.pdf…]()
[Uploading layout.pdf…]()
[Uploading spans.pdf…]()
[math.md](https://github.com/user-attachments/files/16647447/math.md)

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.7.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
Please re upload pdf files.

**Comment by Schorakbi** [comment]
Yeah i am sorry 
[layout.pdf](https://github.com/user-attachments/files/16647653/layout.pdf)
[math.md](https://github.com/user-attachments/files/16647654/math.md)
[origin.pdf](https://github.com/user-attachments/files/16647655/origin.pdf)
[spans.pdf](https://github.com/user-attachments/files/16647656/spans.pdf)

**Comment by myhloli** [comment]
We have noticed this problem and fixed it in the following pr：

https://github.com/opendatalab/MinerU/pull/447

**Comment by Schorakbi** [comment]
Thank you so much

**Comment by Schorakbi** [comment]
I got the exact same result with threshold=0.3 0.25 0.2 
btw i am using a server and endpoint as shown with fastapi 
```
from fastapi import FastAPI, UploadFile, File, Form
from pydantic import BaseModel
import os
from pathlib import Path
from typing import Optional
from magic_pdf.rw.DiskReaderWriter import DiskReaderWriter
from magic_pdf.rw.AbsReaderWriter import AbsReaderWriter
import magic_pdf.model as model_config
from magic_pdf.tools.common import do_parse
from loguru import logger

app = FastAPI()

class ParseRequest(BaseModel):
    output_dir: Optional[str] = ""
    method: Optional[str] = "auto"

@app.post("/extract-text/")
async def extract_text(output_dir: Optional[str] = Form(None), method: Optional[str] = Form("auto"), file: UploadFile = File(...)):
    try:
        # Define the upload and output directories
        upload_dir = Path("./uploads")
        output_dir = Path(output_dir) if output_dir else upload_dir / "output"
        upload_dir.mkdir(parents=True, exist_ok=True)
        output_dir.mkdir(parents=True, exist_ok=True)
        
        # Define the local path to store the uploaded file
        local_path = upload_dir / file.filename
        with open(local_path, "wb") as f:
            f.write(await file.read())
        
        # Configure the model
        model_config.__use_inside_model__ = True
        model_config.__model_mode__ = "full"
        
        # Processing the PDF
        def read_fn(path):
            disk_rw = DiskReaderWriter(os.path.dirname(path))
            return disk_rw.read(os.path.basename(path), AbsReaderWriter.MODE_BIN)
        
        def parse_doc(doc_path: str):
            file_name = str(Path(doc_path).stem)
            pdf_data = read_fn(doc_path)
            do_parse(output_dir, file_name, pdf_data, [], method)
        
        # Process the uploaded PDF
        parse_doc(str(local_path))
        
        return {"status": "success", "output_dir": str(output_dir)}
    except Exception as e:
        logger.exception(e)
        return {"error": str(e)}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)

# uvicorn server:app --reload 
```

**Comment by myhloli** [comment]
We lost many lines in this pdf，this is due to various reasons.
1. model output lost block.
We can get `model.pdf` in this pr by `-d true`
https://github.com/opendatalab/MinerU/pull/397/files

[model.pdf](https://github.com/user-attachments/files/16648408/model.pdf)

You can see that some of the boxes are not accurate and overlap each other, and there are some missing ones, as shown in the following figure.
<img width="545" alt="image" src="https://github.com/user-attachments/assets/fab06b7c-b7f6-4bc8-ae5e-c79fc1c9ee64">

If we lost same block in model output，in subsequent steps, these areas remain missing.

2.  ocr init args `det_db_box_thresh`

The current default parameters are `det_db_thresh=0.3, det_db_box_thresh=0.6 `
These are classic parameters that are suitable for most OCR samples, but in cases with many inline formulas, there may be some 'lines' missing.
[spans_defult.pdf](https://github.com/user-attachments/files/16648428/spans_defult.pdf)
<img width="573" alt="image" src="https://github.com/user-attachments/assets/c4583e3e-6fb8-4db4-bf4d-9c2809f60fac">
<img width="557" alt="image" src="https://github.com/user-attachments/assets/d9a488e3-3b35-4001-83a6-ffbdf841eaa2">

We noticed this problem，and try many docs and args，finally，
`det_db_thresh=0.3, det_db_box_thresh=0.3` is a fairly suitable parameter.

[spans_det_db_box_thresh=0.3.pdf](https://github.com/user-attachments/files/16648525/spans_det_db_box_thresh.0.3.pdf)
<img width="583" alt="image" src="https://github.com/user-attachments/assets/7a49d129-59ca-4dbb-b51d-d828e5e7fc09">
<img width="565" alt="image" src="https://github.com/user-attachments/assets/92a24365-ca74-4613-8771-14ce3a2db310">

3. another ocr init args `det_db_thresh`
In default `det_db_thresh=0.3`, even though we changed det_db_box_thresh to 0.3, we still lose some text lines. like this 
<img width="527" alt="image" src="https://github.com/user-attachments/assets/9b4a2c11-839f-4c2e-81ce-70ff9ff8e729">
So we can try setting an extremely low threshold, such as `det_db_thresh=0.1, det_db_box_thresh=0.1`

[spans_0.1.pdf](https://github.com/user-attachments/files/16648692/spans_0.1.pdf)

<img width="566" alt="image" src="https://github.com/user-attachments/assets/62ed9511-e7ec-4fa6-9277-4f6fe9b6b9fc">

You will found them.


There are some explanations from "Qwen" here:

In the DB (Differentiable Binarization) algorithm, which is used for text detection, the parameters det_db_thresh and det_db_box_thresh play important roles in determining the quality of the detected text regions. Here’s what they do:
- det_db_thresh:
Purpose: This parameter controls the binarization threshold applied to the probability map generated by the model.
Effect: A lower value means more pixels will be considered part of a text region, potentially leading to fewer false negatives but possibly more false positives. A higher value means fewer pixels will be considered part of a text region, which could result in more false negatives but fewer false positives.
Typical Use: It is used to create a binary map from the probability map, where values above this threshold are considered as text and values below are considered as non-text.
- det_db_box_thresh:
Purpose: This parameter controls the threshold for the average score within a bounding box.
Effect: A higher value means only bounding boxes with a high average score will be kept, which can reduce the number of false detections. A lower value means more bounding boxes will be retained, potentially including more true text regions but also more false positives.
Typical Use: After the binary map is created, this threshold is used to filter out bounding boxes based on the average score of the pixels inside them. Only those bounding boxes with an average score above this threshold are considered valid text regions.

These thresholds are crucial for balancing the trade-off between precision and recall in text detection tasks. Adjusting them can help optimize the performance of the DB algorithm for different scenarios, especially when dealing with challenging cases like documents with many inline formulas or varying text sizes and orientations.

**Comment by Schorakbi** [comment]
Yeah thank you for your very clear explanation but something i don't understand that's I changed the values many times but this block of text still not getting recognized i don't understand why and this sentence too
![image](https://github.com/user-attachments/assets/22b7d191-fdb3-41f4-a774-2d4bcbbc9ea9)
![image](https://github.com/user-attachments/assets/99b06bf4-b274-40ff-991a-f0c3af9a2ecd)

**Comment by myhloli** [comment]
Because of model output lost block.
If we lost some block in model output，in subsequent steps, these areas remain missing.

**Comment by Schorakbi** [comment]
Ah ok yeah and for now I work with the model output losing block until it get fixed?

**Comment by myhloli** [comment]
> Ah ok yeah and for now I work with the model output losing block until it get fixed?
> 
> 

Yes，we will fix it, but model's bug need more time to fixed.

**Comment by Schorakbi** [comment]
Yeah ok thank you so much for the clear explanation and your time on this amazing project

**Comment by myhloli** [comment]
You are welcome.
